services:
  traefik:
    image: ${TRAEFIK_IMAGE}
    container_name: traefik
    hostname: traefik
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "traefik",
          "healthcheck",
          "--ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    command:
      - --providers.docker=true
      - --providers.file.filename=/etc/traefik/dynamic.yml
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yaml:/etc/traefik/dynamic.yml:ro
      - ./traefik/tls/mydomain.crt:/certs/mydomain.crt:ro
      - ./traefik/tls/mydomain.key:/certs/mydomain.key:ro
    labels:
      traefik.enable: true
      traefik.http.routers.traefik.rule: Host(`traefik.${HTTP_DOMAIN}`)
      traefik.http.routers.traefik.service: api@internal
      traefik.http.routers.traefik.entrypoints: websecure
      traefik.http.routers.traefik.tls.domains[0].main: traefik.${HTTP_DOMAIN}
      traefik.http.routers.traefik.tls: true
      traefik.http.routers.traefik.tls.options: default
      traefik.http.routers.traefik.priority: 1
      traefik.http.routers.traefik.middlewares: oauth2-auth-administration@docker
      traefik.http.services.test.loadbalancer.server.port: 8080

      traefik.http.middlewares.oauth2-auth-administration.forwardauth.address: http://oauth2-proxy:4180/oauth2/auth?allowed_groups=Administration
      traefik.http.middlewares.oauth2-auth-administration.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.oauth2-auth-administration.forwardauth.authResponseHeaders: X-Auth-Request-User,X-Auth-Request-Email,X-Auth-Request-Groups,Authorization,Set-Cookie
      traefik.http.middlewares.oauth2-auth-administration.forwardauth.authRequestHeaders: Cookie
    networks:
      dmz:
        ipv4_address: 172.20.0.3
      dcn:
