
services:
  test-service:
    build:
      context: ..
      dockerfile: docker/test-service/Dockerfile
      network: host
    image: docker-test-service:latest
    hostname: test-service
    container_name: test-service
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "8080:8080"
    volumes:
      - ../src:/app/src:ro
    restart: unless-stopped
