
services:
  test-service:
    build:
      context: ..
      dockerfile: docker/test-service/Dockerfile
      # network: host
    image: ${TEST_SERVICE_IMAGE}
    hostname: test-service
    container_name: test-service
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://test-service:8080/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      oauth2-proxy:
        condition: service_healthy
    labels:
      traefik.enable: true
      traefik.http.routers.test-service.rule: Host(`test-service.${HTTP_DOMAIN}`)
      traefik.http.routers.test-service.entrypoints: websecure
      traefik.http.routers.test-service.tls: true
      traefik.http.routers.test-service.tls.options: default
      traefik.http.routers.test-service.service: test-service
      traefik.http.routers.test-service.middlewares: oauth2-auth@docker
      traefik.http.services.test-service.loadbalancer.server.port: 8080

      traefik.http.middlewares.oauth2-auth.forwardauth.address: http://oauth2-proxy:4180/oauth2/auth
      traefik.http.middlewares.oauth2-auth.forwardauth.trustForwardHeader: true
      traefik.http.middlewares.oauth2-auth.forwardauth.authResponseHeaders: X-Auth-Request-User,X-Auth-Request-Email,Authorization,Set-Cookie
      traefik.http.middlewares.oauth2-auth.forwardauth.authRequestHeaders: Cookie
      traefik.docker.network: dmz
    expose:
      - 8080
    networks:
      dmz:
      smo:
