services:
  traefik:
    image: ${TRAEFIK_IMAGE}
    hostname: traefik
    container_name: traefik
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "traefik",
          "healthcheck",
          "--ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    command:
      - --log.level=${LOG_LEVEL}
      - --ping
      - --ping.entrypoint=web
      - --api.dashboard=true
      - --api.insecure=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yaml:/etc/traefik/traefik.yml:ro
      - ./traefik/tls/:/certs/:ro