services:
  oauth2-proxy:
    build:
      context: ./oauth2-proxy
    image: ${OAUTH2_PROXY_IMAGE}-custom
    container_name: oauth2-proxy
    hostname: oauth2-proxy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://oauth2-proxy:4180/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    command:
      - --config=/etc/oauth2-proxy.cfg
      # - --logging-level=debug
    environment:
      OAUTH2_PROXY_CLIENT_ID: oauth2-proxy
      OAUTH2_PROXY_CLIENT_SECRET: Kp8bJ4SXszM0WXlhak3eHlcse2gAw84vaoGGmJvUy2U
      SSL_CERT_FILE: /etc/ssl/certs/mydomain-ca.crt
    volumes:
      - ./oauth2-proxy/oauth2-proxy.cfg:/etc/oauth2-proxy.cfg
      - ./traefik/tls/mydomain-ca.crt:/etc/ssl/certs/mydomain-ca.crt:ro
    depends_on:
      keycloak:
        condition: service_healthy
    labels:
      traefik.enable: true
      traefik.http.routers.oauth2-proxy.rule: Host(`oauth2-proxy.${HTTP_DOMAIN}`)
      traefik.http.routers.oauth2-proxy.entrypoints: websecure
      traefik.http.routers.oauth2-proxy.tls: true
      traefik.http.routers.oauth2-proxy.tls.options: default
      traefik.http.routers.oauth2-proxy.priority: 5
      traefik.http.services.oauth2-proxy.loadbalancer.server.port: 4180
    extra_hosts:
      keycloak.smo.o-ran-sc.org: 172.20.0.3
    expose:
      - 4180
    networks:
      dmz:
