entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

  ping:
    address: ":8082"

ping:
  entryPoint: "ping"

api:
  dashboard: true
  insecure: false

log:
  level: DEBUG

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
